#!/bin/bash
cd $(cd `dirname $0`; pwd)
# Path = $(cd `dirname $0`; pwd)
echo "------------------------------"
Path=`pwd`
echo "Path: " $Path
echo ""
echo "Please confirm the path. Press enter to continue."
read
echo "------------------------------"
git add .
echo "------------------------------"
read -p "Commit info: " C_info
git commit -m "$C_info"
echo "------------------------------"
git push -u origin master
